version: '3.3'

services:

  onos:
    image: onosproject/onos:latest
    restart: always
    ports:
      - 8181:8181
      - 6633:6633
      - 6653:6653
    container_name: onos
    
  containernet:
    depends_on:
      - onos
    image: containernet/containernet:latest
    command: sudo /midori/start_midori.sh start
    ports:
      - 8000:8000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/Users/scox/dev/midori:/midori"
    privileged: true
    pid: host
    tty: true
    container_name: containernet
    
  redis:
    image: redislabs/redisgraph:2.8.9
    restart: always
    ports:
      - 6379:6379
    container_name: redis
